// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwM1Vxx3UYkE_uKSjrc4n2WDrCWXdPTXE',
    appId: '1:999445358427:web:96fe6ae9e6166b84931c7e',
    messagingSenderId: '999445358427',
    projectId: 'tasktitan-4942a',
    authDomain: 'tasktitan-4942a.firebaseapp.com',
    storageBucket: 'tasktitan-4942a.firebasestorage.app',
    measurementId: 'G-M6XSN20SS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0jleS8Aua6x0kRo9kTmYEjXgLHQCiWo',
    appId: '1:999445358427:android:a029343a4a856a22931c7e',
    messagingSenderId: '999445358427',
    projectId: 'tasktitan-4942a',
    storageBucket: 'tasktitan-4942a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizpOcqwTXJK6YG_KnXWywMgWrfUeEYyg',
    appId: '1:999445358427:ios:76a7e25f12b79187931c7e',
    messagingSenderId: '999445358427',
    projectId: 'tasktitan-4942a',
    storageBucket: 'tasktitan-4942a.firebasestorage.app',
    iosBundleId: 'com.example.taskTitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizpOcqwTXJK6YG_KnXWywMgWrfUeEYyg',
    appId: '1:999445358427:ios:76a7e25f12b79187931c7e',
    messagingSenderId: '999445358427',
    projectId: 'tasktitan-4942a',
    storageBucket: 'tasktitan-4942a.firebasestorage.app',
    iosBundleId: 'com.example.taskTitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwM1Vxx3UYkE_uKSjrc4n2WDrCWXdPTXE',
    appId: '1:999445358427:web:436ea28272430955931c7e',
    messagingSenderId: '999445358427',
    projectId: 'tasktitan-4942a',
    authDomain: 'tasktitan-4942a.firebaseapp.com',
    storageBucket: 'tasktitan-4942a.firebasestorage.app',
    measurementId: 'G-Y0YJ90BPCM',
  );
}
